model_dir: '/CompMicro/projects/virtualstaining/kidneyslice/2019_02_15_kidney_slice/MBL_DL_image_translation/temp/translation_model_adam_mae'
image_dir: '/CompMicro/projects/virtualstaining/kidneyslice/2019_02_15_kidney_slice/MBL_DL_image_translation/data'
preprocess_dir: '/CompMicro/projects/virtualstaining/kidneyslice/2019_02_15_kidney_slice/MBL_DL_image_translation/temp/tile_small'
dataset:
  input_channels: [2]
  target_channels: [1]
  slice_ids: [10, 11, 12, 13, 14, 15]
images:
    image_format: 'zyx'
    image_ext: '.tif'
    name_format: sms
    pred_chan_name: 'pred'
save_to_image_dir: False
data_split: test
save_figs: True
metrics:
    metrics: ['r2', 'corr', 'ssim']
    metrics_orientations: ['xy', 'xyz', 'xz', 'yz']